export const SNACKBAR_ADD_NEW = "SNACKBAR_ADD_NEW";
export const SNACKBAR_DISPLAY_NEXT = "SNACKBAR_DISPLAY_NEXT";
export const SNACKBAR_HIDE_CURRENT = "SNACKBAR_HIDE_CURRENT";
export const SNACKBAR_REMOVE_CURRENT = "SNACKBAR_REMOVE_CURRENT";
