export const SNACKBAR_ADD_NEW = "SNACKBAR_ADD_NEW";
export const SNACKBAR_DISPLAY_NEXT = "SNACKBAR_DISPLAY_NEXT";
export const SNACKBAR_HIDE_CURRENT = "SNACKBAR_HIDE_CURRENT";
export const SNACKBAR_REMOVE_CURRENT = "SNACKBAR_REMOVE_CURRENT";

export const SET_STOCKS = "SET_STOCKS";
export const SET_SELECTED_STOCK = "SET_SELECTED_STOCK";
export const SET_DATA_POINTS = "SET_DATA_POINTS";
export const UNSELECT_STOCK = "UNSELECT_STOCK";
